### ISSUE TITLE
Impact of current changes in the CDS API and open-meteo API?

### ISSUE THREAD

**Issue by MxNl** [tpisel/openmeteo#8]
Hello,

I am really grateful for your package here! It helps us to overcome the temporary out-of-service issue of EOBS data. 
Therefore, I wanted to ask if you are planning to update this package regarding the current changes of the CDS API and - subsequently - changes of the open-meteo API. I guess that this package here will also affected by these changes. I also raised an issue in [open-meteo](https://github.com/open-meteo/open-meteo/discussions/657).

Thanks a lot!

**Comment by tpisel** [comment]
Thanks! I'll keep an eye on what changes may happen in the main project and see what may be necessary here if any.
